---
- name: Staging server Deployment
  hosts: stageserver
  become_user: root
  become: true
  vars:
    repo_path: nrbaskar/angularcourse:{{DOCKER_TAG}}
    dest_path: /home/ec2-user/{{DOCKER_TAG}}
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Pull docker image
      docker_image:
        name: nrbaskar/angularcourse
        tag: "{{DOCKER_TAG}}"
        source: pull
    - name: create directory
      file:
        state: directory
        dest: "{{dest_path}}"
    - name: copy website to the host
      copy:
        src: ./
        dest: "{{dest_path}}"
    # Install NodeJS library
    # using multiple shell commands
    - name: Install Nodejs & AngularJS
      shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -'
    # If other package are required mention the package name in "name"
    # eg: ngix, curl, wget, apache2, nodejs
    - name: Install reqired packages
      yum:
        name: nodejs
        state: present
    - name: Install reqired packages
      command: sudo npm install -g @angular/cli
    - name: Install npm installation
      command: npm install
    - name: Install application/libraries
      command: ng build
    - name: Start service
      command: ng serve --host 0.0.0.0 --port 4200
      args:
        chdir: "{{ dest_path }}"
