---
- name: Staging server Deployment
  hosts: stageserver
  become_user: root
  become: true
  vars:
    repo_path: nrbaskar/angularcourse:{{DOCKER_TAG}}
    dest_path: /home/ec2-user/{{DOCKER_TAG}}
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Pull docker image
      docker_image:
        name: nrbaskar/angularcourse
        tag: "{{DOCKER_TAG}}"
        source: pull
    - name: create directory
      file:
        state: directory
        dest: "{{dest_path}}"
    - name: copy website to the host
      copy:
        src: ./
        dest: "{{dest_path}}"
    # Install NodeJS library
    # using multiple shell commands
    - name: Install Node.js 16.x repository
      get_url:
        url: https://rpm.nodesource.com/setup_16.x
        dest: /tmp/setup_16.x.sh
        mode: 'u+x'
    - name: Run Node.js 16.x setup script
      shell: /tmp/setup_16.x.sh
    - name: Install required packages
      yum:
        name: nodejs
        state: present
    - name: Install Angular CLI
      npm:
        name: '@angular/cli'
        global: yes
        state: present
    - name: Install npm packages
      npm:
        path: "{{ dest_path }}"
        state: present
    - name: Build and serve the Angular application
      shell: ng serve
      args:
        chdir: "{{ dest_path }}"
    - name: Install PM2
      npm:
        name: pm2
        global: yes
        state: present
    - name: Start PM2 service
      shell: pm2 start ./src/index.html --name "{{DOCKER_TAG}}-Service"
      args:
        chdir: "{{ dest_path }}"
