---
- name: Staging server deployment
  hosts: stageserver
  become_user: root
  become: true
  vars:
    repo_path: nrbaskar/angularcourse:{{DOCKER_TAG}}
    dest_path: /home/ec2-user/{{DOCKER_TAG}}
  tasks:
    - name: Install dependencies
      yum:
        name:
          - python-pip
          - docker
        state: present
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Pull Docker image
      docker_image:
        name: nrbaskar/angularcourse
        tag: "{{DOCKER_TAG}}"
        source: pull
    - name: Build Angular project
      shell: ng build --prod --output-path="{{dest_path}}/dist"
      args:
        chdir: "{{ playbook_dir }}/path/to/angular/project"
    - name: Copy necessary files to destination path
      copy:
        src: "{{ playbook_dir }}/path/to/angular/project/dist"
        dest: "{{ dest_path }}"
        remote_src: yes
    - name: Install and configure web server
      yum:
        name: httpd
        state: present
      notify:
        - start web server
    - name: Configure web server
      template:
        src: "{{ playbook_dir }}/path/to/httpd.conf.template"
        dest: /etc/httpd/conf/httpd.conf
      notify:
        - restart web server
    - name: Start web server
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Restart web server
      service:
        name: httpd
        state: restarted
