- name: Staging server Deployment
  hosts: stageserver
  become_user: root
  become: true
  vars:
    repo_path: nrbaskar/angularcourse:{{ DOCKER_TAG }}
    dest_path: /home/ec2-user/{{ DOCKER_TAG }}
    app_name: angular-crash-course
  tasks:
    - name: Install python pip
      yum:
        name: python-pip
        state: present
    - name: Install docker
      yum:
        name: docker
        state: present
    - name: start docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Pull docker image
      docker_image:
        name: nrbaskar/angularcourse
        tag: "{{ DOCKER_TAG }}"
        source: pull
    - name: create directory
      file:
        state: directory
        dest: "{{ dest_path }}"
    - name: copy website to the host
      copy:
        src: ./
        dest: "{{ dest_path }}"
    - name: Install Nodejs & AngularJS
      shell: 'curl --silent --location https://rpm.nodesource.com/setup_16.x | bash -'
    - name: Install required packages
      yum:
        name: nodejs
        state: present
    - name: Install project dependencies
      command: npm install
      args:
        chdir: "{{ dest_path }}"
    - name: Install Angular CLI
      command: sudo npm install -g @angular/cli
    - name: Install Node packages
      npm:
        path: "{{ dest_path }}"
    - name: Build the application
      command: ng build --configuration production
      args:
        chdir: "{{ dest_path }}"
    - name: Install PM2
      npm: name=pm2 global=yes state=present
    - name: Start service
      pm2:
        name: "{{angular-crash-course}}"
        script: "{{ dest_path }}/dist/{{angular-crash-course}}/server/main.js"
        autorestart: true
        watch: "{{ dest_path }}/dist/{{angular-crash-course}}"
